---
  apiVersion: v2
  name: mitb-argocd
  version: 1.0.0
  type: application
  dependencies:
    - name: argo-cd
      version: 7.3.2
      repository: https://argoproj.github.io/argo-helm
    - name: argocd-image-updater
      version: 0.9.6
      repository: https://argoproj.github.io/argo-helm