steps:
  - name: ":helm: Helm Tarball Update"
    key: "helm-dep-up"
    plugins:
      - datumforge/helm#e23d21a20c4254119fda11218d994054f7469681: 
          user:
            name: datum-bender
            email: bender@datum.net
  
  - label: ":helm: docs"
    depends_on:
      - helm-dep-up
    plugins:
      - docker#v5.10.0:
          image: "jnorwood/helm-docs:latest"
          volume: ["`pwd`:/helm-docs"]
          entrypoint: "/usr/bin/helm-docs"
          command: ["helm", "docs", "--document-dependency-values"]
      - datumforge/git-commit#8d87ed0c26215f7bf4277e0752b8faffb0a6cdd0:
          message: "Updated helm docs"
          https: true
          user:
            name: datum-bender
            email: bender@datum.net
  
  - label: ":trivy: scan"
    command: "echo '--- Running the Trivy security scanner'"
    plugins:
      - equinixmetal-buildkite/trivy#v1.18.5:
          severity: "CRITICAL,HIGH"
          security-checks: "config,secret"
  
  - label: ":helm: lint"
    depends_on:
      - helm-dep-up
    plugins:
      - docker#v5.10.0:
          image: "alpine/helm"
          command: 
            - "lint"
